### ISSUE TITLE
docs: Discord Invite Link invalid

### ISSUE THREAD

**Issue by Tokugero** [uptime-industries/compute-blade#10]
Discord link in footer results in "Invite Invalid" on multiple computers.

Getting the link from the Discord Discover search yields https://discord.gg/invite/uptime-industries-952334175501946902, but perhaps there's another step required to generate this link in the intended way.

**Comment by bowenjw** [comment]
It worked for me
![image](https://github.com/user-attachments/assets/57977202-4aa3-4fd4-b975-6731a51c4f97)

**Comment by Tokugero** [comment]
It might just be from my house, but here's some screenshots from a machine without discord installed or ever used (debian chrome)

![image](https://github.com/user-attachments/assets/f3749271-2257-4ef2-a0a5-9fb248ff162d)

URL of the 404 redirect: 
https://discord.com/api/v9/invites/uptime-industries?with_counts=true&with_expiration=true
Message from the 404:
{"message": "Unknown Invite", "code": 10006}

If no one else is having this behavior then this can probably just be closed as a one-off user though.

**Comment by bowenjw** [comment]
I see it I will fix it Thanks
