### ISSUE TITLE
Documentation - Doubled text

### ISSUE THREAD

**Issue by equinoxel** [uptime-industries/compute-blade#17]
Page: https://docs.computeblade.com/blade/getting-started/assembly/#compute-module
Browser: Firefox
Description:
The text in the warning box is doubled:
![image](https://github.com/user-attachments/assets/98ff16cb-8404-48b0-b289-27be0d4002b6)

**Comment by Ethazeriel** [comment]
There's a few of these created in the most recent commit, should be fixed by #16
