### ISSUE TITLE
docs: minor spelling mistake on homepage

### ISSUE THREAD

**Issue by Jmaasy** [uptime-industries/compute-blade#22]
On the homepage it notes "Gettting Started" instead of Getting Started on the button.
<img width="346" alt="Screenshot 2024-09-02 at 21 47 07" src="https://github.com/user-attachments/assets/ebc75afb-4b2e-4d24-afcb-08d15d62dbb6">

**Comment by bowenjw** [comment]
Haha I will get that fixed

**Comment by bowenjw** [comment]
Closed with commit [`aef95ed`](https://github.com/uptime-industries/compute-blade/commit/aef95ede7d6157058b8728eeea067b00391acac3)
