### ISSUE TITLE
No Updates on Production - Still waiting for 10"  Rack Cluster and Metal Rack

### ISSUE THREAD

**Issue by andar1an** [uptime-industries/compute-blade#24]
I have emailed support 2 times, messaged on LinkedIn, and have made sure I didn't miss an updates on Kickstarter. 

What is the status of the Rack Clusters? 

Shipping started December 2023, it is now coming onto December 2024.

**Comment by bowenjw** [comment]
This issues is not related to this repository

**Comment by andar1an** [comment]
This is the "compute blade" repo, and there is no responce to emails, LinkedIn messages, or kickstarter queries, than this is what there is. 

I don't have discord, and would like to make aure this lack of communication to backers is visible.
