### ISSUE TITLE
Compute Blades Not Working

### ISSUE THREAD

**Issue by andar1an** [uptime-industries/compute-blade#38]
Compute blades not working because I can't plug them in.

```sh
Backer 1017

Order:
10" Cluster + 19" Metal Rack Upgrade

Order Date: 
July 2023

Order Cost:
Over 900 Euro

Beta Blade Backer:
Yes
```
I spoke to someone at the beginning of September on LinkedIn who informed me the reason my units had not been shipped was because of the plastic rack bottleneck. 

I ordered the 19" Metal Rack when I backed, so I do not need the plastic rack. You can just not make me one.

I was informed that my units and the metal rack would be shipped. 

It is now November and I have had no update. It is impossible to get responses on Kickstarter, LinkedIn, or through email, so I am creating an issue once again. 

May I please get a status update on my blades?

The delay has made them obsolete in my infrastructure, but I would still like what I payed for. Alternatively, happy to accept a refund. 

Thanks.

**Comment by bowenjw** [comment]
This is the the place for request for backer please send us an email at `support@computeblade.com` for your request

**Comment by andar1an** [comment]
Been another 8 days lol.
